### ISSUE TITLE
styled-components/native

### ISSUE THREAD

**Issue by IljaDaderko** [jameslnewell/styled-components-grid#2]
Was trying to re-write this for react-native app but implementation through `styled-components-breakpoint` is a bit confusing. I assume we don't need it in native project at all, but it would be nice to support custom breakpoints like `small` (iphone 5s), `medium` iphone 7, `large` iphone 7 plus for example. Any advice on tackling these in native project without third party libraries? :)

**Comment by jameslnewell** [comment]
👋 

I'm sorry, I haven't got any experience with react native. Instead of duplicating efforts, could we a "native" file inside this package which has the import changed from `styled-components` to `styled-components/native` (might also need a native file in `styled-components-breakpoint`). Or are there other differences that apply?

The `map` method of `styled-components-breakpoint` applies a "mixin" for each breakpoint provided. e.g.

```js
map(100, width => `width: ${width}%;`);
```
```css
width: 100%;
```

```js
map({mobile: 100, tablet: 50}, width => `width: ${width}%;`);
```
```css
@media (min-width: 0) {
  width: 100%;
}

@media (min-width: 737px) {
  width: 50%;
}
```

https://github.com/jameslnewell/styled-components-breakpoint#mapval-fn-breakpoints
https://github.com/jameslnewell/styled-components-breakpoint/blob/master/src/index.js

**Comment by jameslnewell** [comment]
Guessing there's no breakpoints in react-native? Your device specific styles idea might be able to be implemented something like this:

```js
import DeviceInfo from 'react-native-device-info';

const defaultBreakpoints = {
  small: ['iPhone 4', 'iPhone 5'], 
  medium: ['iPhone 6', 'iPhone 7'],
  large: []
};

const breakpoint = (name, breakpoints = defaultBreakpoints) => {
  const model = DeviceInfo.getModel();
  if (breakpoints[name].contains(model)) {
    return (...args) => css(...args);
  }
};

```

**Comment by jameslnewell** [comment]
But rather than using specific devices it might be better to stick with the device/screen width like CSS. That looks possible `var {height, width} = Dimensions.get('window');` https://facebook.github.io/react-native/docs/dimensions.html

**Comment by IljaDaderko** [comment]
This was fixed for me via introduction of https://github.com/styled-components/polished

**Comment by zomars** [comment]
Care to explain how this was fixed for you @IljaDaderko ?
